[world]
name = "Nums"
seed = "nums-alpha"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://nums.gg"

[namespace]
default = "NUMS"

[env]
rpc_url = "https://api.cartridge.gg/x/nums-bal/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x03e9de5354a43dcc0daf083da2a87a099ce9ea3cec1e8c442f2f448eed6b9c12"

skip_contracts = ["NUMS-MockVRF", "NUMS-MockNumsToken", "NUMS-MockRewardToken"]

[migration]
order_inits = [
    "NUMS-Setup",
    "NUMS-Minigame",
    "NUMS-Renderer",
    "NUMS-Settings",
    "NUMS-Play",
]
disable_multicall = true

[writers]
"NUMS" = [
    "NUMS-Setup",
    "NUMS-Minigame",
    "NUMS-Renderer",
    "NUMS-Settings",
    "NUMS-Play",
]

[init_call_args]
"NUMS-Minigame" = [
    "0x036017E69D21D6D8c13E266EaBB73ef1f1D02722D86BDcAbe5f168f8e549d3cD", # Denshokan address
]
"NUMS-Play" = [
    "1798758000", # claimable_until
]
"NUMS-Setup" = [
    "0x0e5f10eddc01699dc899a30dbc3c9858148fa4aa0a47c0ffd85f887ffc4653e",  # nums_address
    "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address
    "0x1",                                                                # starterpack_address
    "0x03299ace782ec54afcbf81e31e92d6146649b6c484173e41f4de529f6d504fe8", # forwarder_address
    "0x041aad5a7493b75f240f418cb5f052d1a68981af21e813ed0a35e96d3e83123b", # owner_address
]
