packages:
  - "client"
  - "contracts/tokens"
catalog:
  "@cartridge/connector": "0.13.9"
  "@cartridge/controller": "0.13.9"
  "@cartridge/presets": "0.5.2"
  "@cartridge/ui": "github:cartridge-gg/ui#a823aea"
  "@dojoengine/core": "1.8.8"
  "@dojoengine/sdk": "1.9.0"
  "@dojoengine/torii-client": "1.8.2"
  "@dojoengine/torii-wasm": "1.8.2"
  "@dojoengine/utils": "1.8.4"
