world_address = "0x003f15a50317f4f9b74ceacb36322dc9373a8912924fb7a32ae6f314fd1cab4f"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = ["NUMS-TrophyProgression", "NUMS-QuestProgression"]

[erc]
metadata_updates = true
