world_address = "0x00c7cd2221dbeb8c3a098d5300e4758277dda40bf7e64bec1fb5cae2aa077b1d"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = ["NUMS-TrophyProgression", "NUMS-QuestProgression"]

[erc]
metadata_updates = true
