world_address = "0x079ddb00f5186905686fe3c5e5cf8aa7f904fa294a3b9415fccdf3016fc219a4"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = [
  "NUMS-TrophyProgression",
  "NUMS-QuestProgression",
  "NUMS-BundleIssued",
]

[erc]
metadata_updates = true
