world_address = "0x02fd76be329954d0e0d2715b0a4c6f3c72c7ec5254333d2530687e86f0ebeb2b"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = ["NUMS-TrophyProgression", "NUMS-QuestProgression"]

[erc]
metadata_updates = true
