import type { Meta, StoryObj } from "@storybook/react-vite";
import { GameScene } from "./game-scene";
import { Power, PowerType } from "@/types/power";
import { Trap, TrapType } from "@/types/trap";

const meta = {
  title: "Layouts/Game Scene",
  component: GameScene,
  parameters: {
    layout: "padded",
  },
  globals: {
    backgrounds: {
      value: "purple",
    },
  },
  argTypes: {
    currentNumber: {
      control: "number",
      description: "The current number displayed",
    },
    nextNumber: {
      control: "number",
      description: "The next number to be displayed",
    },
    variant: {
      control: "select",
      options: ["default"],
      description: "The visual variant",
    },
    size: {
      control: "select",
      options: ["md"],
      description: "The size variant",
    },
  },
} satisfies Meta<typeof GameScene>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    currentNumber: 162,
    nextNumber: 679,
    minNumber: 1,
    maxNumber: 999,
    powers: [
      { power: new Power(PowerType.Reroll) },
      { power: new Power(PowerType.High), status: "lock" as const },
      { power: new Power(PowerType.Low) },
    ],
    slots: [
      { value: 1 },
      { value: 0 },
      { value: 0, trap: new Trap(TrapType.Lucky) },
      { value: 0 },
      { value: 0 },
      { value: 0, trap: new Trap(TrapType.Windy) },
      { value: 0 },
      { value: 0 },
      { value: 0, trap: new Trap(TrapType.Magnet) },
      { value: 0 },
      { value: 0 },
      { value: 0, trap: new Trap(TrapType.Bomb) },
      { value: 0 },
      { value: 0 },
      { value: 0, trap: new Trap(TrapType.UFO) },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 999 },
    ],
    stages: [
      {},
      {},
      {},
      { gem: true },
      {},
      {},
      {},
      {},
      {},
      { gem: true },
      {},
      { breakeven: true },
      {},
      {},
      {},
      { gem: true },
      {},
      { crown: true },
    ],
    className: "h-[calc(100vh-32px)] md:h-full",
  },
};

export const Rescuable: Story = {
  args: {
    currentNumber: 313,
    nextNumber: 679,
    minNumber: 1,
    maxNumber: 999,
    powers: [{ power: new Power(PowerType.Reroll) }, {}, {}],
    slots: [
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 300 },
      { value: 312 },
      { value: 315 },
      { value: 330 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
    ],
    stages: [
      {},
      { gem: true },
      {},
      {},
      {},
      { gem: true },
      {},
      {},
      {},
      { gem: true },
      {},
      { breakeven: true },
      {},
      { gem: true },
      {},
      {},
      {},
      { crown: true },
    ],
    className: "h-[calc(100vh-32px)] md:h-full",
  },
};

export const GameOver: Story = {
  args: {
    currentNumber: 313,
    nextNumber: 679,
    minNumber: 1,
    maxNumber: 999,
    powers: [{}, {}, {}],
    slots: [
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 300 },
      { value: 312 },
      { value: 315 },
      { value: 330 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
      { value: 0 },
    ],
    stages: [
      {},
      { gem: true },
      {},
      {},
      {},
      { gem: true },
      {},
      {},
      {},
      { gem: true },
      {},
      { breakeven: true },
      {},
      { gem: true },
      {},
      {},
      {},
      { crown: true },
    ],
    className: "h-[calc(100vh-32px)] md:h-full",
  },
};
