[package]
name = "collection"
version = "0.0.0"
edition.workspace = true

[dependencies]
game_components.workspace = true
graffiti.workspace = true
openzeppelin.workspace = true
alexandria_encoding.workspace = true
starknet.workspace = true

[dev-dependencies]
cairo_test.workspace = true

[[target.starknet-contract]]
sierra = true
casm = false
