[world]
name = "Nums"
seed = "nums-alpha.1"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://nums.gg"


[namespace]
default = "nums"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x047a8bfb23061af003dc4075f611221592ece0deb7b1d5ab4fabeb6abf49bdfc"
keystore_path = "../../../dev_accounts/nums_key"
#world_address = "0x04ab1fc4b349bfffb69afb68805b517410e43d843dffc4b36b7d9b2b87979b60"

skip_contracts = ["nums-MockVRF"]

[writers]
"nums" = ["nums-game_actions", "nums-config_actions", "nums-jackpot_actions"]

[init_call_args]
"nums-config_actions" = [
    "0x1",                                                                # nums_address = Option::None
    "0x0",                                                                # Option::Some
    "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address 
    "50",                                                                 # burn_pct
]

"nums-claim_actions" = [
    "0x1", # nums_address = Option::None
    "0x0", # Option::Some
    "0x03299ace782ec54afcbf81e31e92d6146649b6c484173e41f4de529f6d504fe8", # forwarder_address
]