[world]
name = "Nums"
seed = "nums"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://nums.gg"


[namespace]
default = "nums"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"

# TODO: config deployer account & set world address
account_address = "0x"
keystore_path = "../../../dev_accounts/nums_key"
#world_address = "0x"

skip_contracts = ["nums-MockVRF", "nums-MockNumsToken", "nums-MockRewardToken"]

[writers]
"nums" = ["nums-game_actions", "nums-config_actions", "nums-jackpot_actions"]

[init_call_args]
"nums-config_actions" = [
    "0x0",                                                                # Option::Some
    "0xe5f10eddc01699dc899a30dbc3c9858148fa4aa0a47c0ffd85f887ffc4653e",   # nums_address 
    "0x0",                                                                # Option::Some
    "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address 
    "50",                                                                 # burn_pct
]

"nums-claim_actions" = [
    "0x0",                                                                # Option::Some
    "0xe5f10eddc01699dc899a30dbc3c9858148fa4aa0a47c0ffd85f887ffc4653e",   # nums_address 
    "0x0",                                                                # Option::Some
    "0x03299ace782ec54afcbf81e31e92d6146649b6c484173e41f4de529f6d504fe8", # forwarder_address
    "1758931200", # claimable_until Sat Sep 27 2025 00:00:00 GMT+0000
]
