world_address = "0x02332b8b17a3ebe27a90100988fb980d5121dc5edb98392c20a3df2f57f9b02a"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = false

[indexing]
world_block = 0
controllers = true
pending = true
polling_interval = 250
contracts = [
    "ERC20:0x222e607cde6c19f110d5edafca0440a74e4c4fe6baa16ddac18ac58cb5ada0e",   # NUMS
    "ERC721:0x02334dc9c950c74c3228e2a343d495ae36f0b4edf06767a679569e9f9de08776", # Denshokan
]


[sql]
historical = ["nums-TrophyProgression"]
