world_address = "0x04ab1fc4b349bfffb69afb68805b517410e43d843dffc4b36b7d9b2b87979b60"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = false

[indexing]
world_block = 2094420
controllers = true
pending = true
polling_interval = 250
max_concurrent_tasks = 2
contracts = [
    "ERC20:0x044e9693a69aff653dddc9d8fca04a11e5d55a79dfc5aba67d78b609e6db48d6", # NUMS
    "ERC20:0x0566e7f2fd30d967019d44027b4096ac6163b10a4489208fe0d179c4f51d5c97", # REW
]


[sql]
historical = ["nums-TrophyProgression"]
