world_address = "0x04cae8373db3191fd986cb3d861f69075d396d04c2fb97f8c0d78a0ad30023bd"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = false

[indexing]
world_block = 2115600
controllers = true
pending = true
polling_interval = 250
max_concurrent_tasks = 2
contracts = [
    "ERC20:0x0112de3f6eae7537692edf4d735b6e253ad2afc531e733d5893b7a048ba26fd1", # NUMS
    "ERC20:0x069683675e2892e4d65088bfbf7170fab0a32f1de7aaa35acd06943ca81252e4", # REW
]


[sql]
historical = ["nums-TrophyProgression"]
