use achievement::types::metadata::{AchievementMetadata, MetadataTrait};
use achievement::types::task::Task as AchievementTask;
use crate::elements::achievements;

// Constants

pub const ACHIEVEMENT_COUNT: u8 = 30;

// Types

#[derive(Copy, Drop)]
pub enum Achievement {
    None,
    GrinderI,
    GrinderII,
    GrinderIII,
    GrinderIV,
    GrinderV,
    ReferenceI,
    ReferenceII,
    ReferenceIII,
    ReferenceIV,
    ReferenceV,
    ReferenceVI,
    ReferenceVII,
    FillerOne,
    FillerTwo,
    FillerThree,
    FillerFour,
    FillerFive,
    StreakOne,
    StreakTwo,
    StreakThree,
    ClaimerOne,
    ClaimerTwo,
    ClaimerThree,
    ClaimerFour,
    ClaimerFive,
    DailyMaster,
    WeeklyMaster,
    KingI,
    KingII,
    KingIII,
}

#[generate_trait]
pub impl AchievementImpl of AchievementTrait {
    fn identifier(self: Achievement) -> felt252 {
        match self {
            Achievement::None => 0,
            Achievement::GrinderI => achievements::grinder::Grinder::identifier(0),
            Achievement::GrinderII => achievements::grinder::Grinder::identifier(1),
            Achievement::GrinderIII => achievements::grinder::Grinder::identifier(2),
            Achievement::GrinderIV => achievements::grinder::Grinder::identifier(3),
            Achievement::GrinderV => achievements::grinder::Grinder::identifier(4),
            Achievement::ReferenceI => achievements::reference::Reference::identifier(0),
            Achievement::ReferenceII => achievements::reference::Reference::identifier(1),
            Achievement::ReferenceIII => achievements::reference::Reference::identifier(2),
            Achievement::ReferenceIV => achievements::reference::Reference::identifier(3),
            Achievement::ReferenceV => achievements::reference::Reference::identifier(4),
            Achievement::ReferenceVI => achievements::reference::Reference::identifier(5),
            Achievement::ReferenceVII => achievements::reference::Reference::identifier(6),
            Achievement::FillerOne => achievements::filler::Filler::identifier(0),
            Achievement::FillerTwo => achievements::filler::Filler::identifier(1),
            Achievement::FillerThree => achievements::filler::Filler::identifier(2),
            Achievement::FillerFour => achievements::filler::Filler::identifier(3),
            Achievement::FillerFive => achievements::filler::Filler::identifier(4),
            Achievement::StreakOne => achievements::streak::Streak::identifier(0),
            Achievement::StreakTwo => achievements::streak::Streak::identifier(1),
            Achievement::StreakThree => achievements::streak::Streak::identifier(2),
            Achievement::ClaimerOne => achievements::claimer::Claimer::identifier(0),
            Achievement::ClaimerTwo => achievements::claimer::Claimer::identifier(1),
            Achievement::ClaimerThree => achievements::claimer::Claimer::identifier(2),
            Achievement::ClaimerFour => achievements::claimer::Claimer::identifier(3),
            Achievement::ClaimerFive => achievements::claimer::Claimer::identifier(4),
            Achievement::DailyMaster => achievements::master::Master::identifier(0),
            Achievement::WeeklyMaster => achievements::master::Master::identifier(1),
            Achievement::KingI => achievements::king::King::identifier(0),
            Achievement::KingII => achievements::king::King::identifier(1),
            Achievement::KingIII => achievements::king::King::identifier(2),
        }
    }

    fn tasks(self: Achievement) -> Span<AchievementTask> {
        match self {
            Achievement::None => [].span(),
            Achievement::GrinderI => achievements::grinder::Grinder::tasks(0),
            Achievement::GrinderII => achievements::grinder::Grinder::tasks(1),
            Achievement::GrinderIII => achievements::grinder::Grinder::tasks(2),
            Achievement::GrinderIV => achievements::grinder::Grinder::tasks(3),
            Achievement::GrinderV => achievements::grinder::Grinder::tasks(4),
            Achievement::ReferenceI => achievements::reference::Reference::tasks(0),
            Achievement::ReferenceII => achievements::reference::Reference::tasks(1),
            Achievement::ReferenceIII => achievements::reference::Reference::tasks(2),
            Achievement::ReferenceIV => achievements::reference::Reference::tasks(3),
            Achievement::ReferenceV => achievements::reference::Reference::tasks(4),
            Achievement::ReferenceVI => achievements::reference::Reference::tasks(5),
            Achievement::ReferenceVII => achievements::reference::Reference::tasks(6),
            Achievement::FillerOne => achievements::filler::Filler::tasks(0),
            Achievement::FillerTwo => achievements::filler::Filler::tasks(1),
            Achievement::FillerThree => achievements::filler::Filler::tasks(2),
            Achievement::FillerFour => achievements::filler::Filler::tasks(3),
            Achievement::FillerFive => achievements::filler::Filler::tasks(4),
            Achievement::StreakOne => achievements::streak::Streak::tasks(0),
            Achievement::StreakTwo => achievements::streak::Streak::tasks(1),
            Achievement::StreakThree => achievements::streak::Streak::tasks(2),
            Achievement::ClaimerOne => achievements::claimer::Claimer::tasks(0),
            Achievement::ClaimerTwo => achievements::claimer::Claimer::tasks(1),
            Achievement::ClaimerThree => achievements::claimer::Claimer::tasks(2),
            Achievement::ClaimerFour => achievements::claimer::Claimer::tasks(3),
            Achievement::ClaimerFive => achievements::claimer::Claimer::tasks(4),
            Achievement::DailyMaster => achievements::master::Master::tasks(0),
            Achievement::WeeklyMaster => achievements::master::Master::tasks(1),
            Achievement::KingI => achievements::king::King::tasks(0),
            Achievement::KingII => achievements::king::King::tasks(1),
            Achievement::KingIII => achievements::king::King::tasks(2),
        }
    }

    fn metadata(self: Achievement) -> AchievementMetadata {
        match self {
            Achievement::None => MetadataTrait::new(
                title: '',
                description: "",
                icon: '',
                points: 0,
                hidden: false,
                index: 0,
                group: '',
                rewards: array![].span(),
                data: "",
            ),
            Achievement::GrinderI => MetadataTrait::new(
                title: achievements::grinder::Grinder::title(0),
                description: achievements::grinder::Grinder::description(0),
                icon: achievements::grinder::Grinder::icon(0),
                points: achievements::grinder::Grinder::points(0),
                hidden: achievements::grinder::Grinder::hidden(0),
                index: achievements::grinder::Grinder::index(0),
                group: achievements::grinder::Grinder::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::GrinderII => MetadataTrait::new(
                title: achievements::grinder::Grinder::title(1),
                description: achievements::grinder::Grinder::description(1),
                icon: achievements::grinder::Grinder::icon(1),
                points: achievements::grinder::Grinder::points(1),
                hidden: achievements::grinder::Grinder::hidden(1),
                index: achievements::grinder::Grinder::index(1),
                group: achievements::grinder::Grinder::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::GrinderIII => MetadataTrait::new(
                title: achievements::grinder::Grinder::title(2),
                description: achievements::grinder::Grinder::description(2),
                icon: achievements::grinder::Grinder::icon(2),
                points: achievements::grinder::Grinder::points(2),
                hidden: achievements::grinder::Grinder::hidden(2),
                index: achievements::grinder::Grinder::index(2),
                group: achievements::grinder::Grinder::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::GrinderIV => MetadataTrait::new(
                title: achievements::grinder::Grinder::title(3),
                description: achievements::grinder::Grinder::description(3),
                icon: achievements::grinder::Grinder::icon(3),
                points: achievements::grinder::Grinder::points(3),
                hidden: achievements::grinder::Grinder::hidden(3),
                index: achievements::grinder::Grinder::index(3),
                group: achievements::grinder::Grinder::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::GrinderV => MetadataTrait::new(
                title: achievements::grinder::Grinder::title(4),
                description: achievements::grinder::Grinder::description(4),
                icon: achievements::grinder::Grinder::icon(4),
                points: achievements::grinder::Grinder::points(4),
                hidden: achievements::grinder::Grinder::hidden(4),
                index: achievements::grinder::Grinder::index(4),
                group: achievements::grinder::Grinder::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ReferenceI => MetadataTrait::new(
                title: achievements::reference::Reference::title(0),
                description: achievements::reference::Reference::description(0),
                icon: achievements::reference::Reference::icon(0),
                points: achievements::reference::Reference::points(0),
                hidden: achievements::reference::Reference::hidden(0),
                index: achievements::reference::Reference::index(0),
                group: achievements::reference::Reference::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ReferenceII => MetadataTrait::new(
                title: achievements::reference::Reference::title(1),
                description: achievements::reference::Reference::description(1),
                icon: achievements::reference::Reference::icon(1),
                points: achievements::reference::Reference::points(1),
                hidden: achievements::reference::Reference::hidden(1),
                index: achievements::reference::Reference::index(1),
                group: achievements::reference::Reference::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ReferenceIII => MetadataTrait::new(
                title: achievements::reference::Reference::title(2),
                description: achievements::reference::Reference::description(2),
                icon: achievements::reference::Reference::icon(2),
                points: achievements::reference::Reference::points(2),
                hidden: achievements::reference::Reference::hidden(2),
                index: achievements::reference::Reference::index(2),
                group: achievements::reference::Reference::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ReferenceIV => MetadataTrait::new(
                title: achievements::reference::Reference::title(3),
                description: achievements::reference::Reference::description(3),
                icon: achievements::reference::Reference::icon(3),
                points: achievements::reference::Reference::points(3),
                hidden: achievements::reference::Reference::hidden(3),
                index: achievements::reference::Reference::index(3),
                group: achievements::reference::Reference::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ReferenceV => MetadataTrait::new(
                title: achievements::reference::Reference::title(4),
                description: achievements::reference::Reference::description(4),
                icon: achievements::reference::Reference::icon(4),
                points: achievements::reference::Reference::points(4),
                hidden: achievements::reference::Reference::hidden(4),
                index: achievements::reference::Reference::index(4),
                group: achievements::reference::Reference::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ReferenceVI => MetadataTrait::new(
                title: achievements::reference::Reference::title(5),
                description: achievements::reference::Reference::description(5),
                icon: achievements::reference::Reference::icon(5),
                points: achievements::reference::Reference::points(5),
                hidden: achievements::reference::Reference::hidden(5),
                index: achievements::reference::Reference::index(5),
                group: achievements::reference::Reference::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ReferenceVII => MetadataTrait::new(
                title: achievements::reference::Reference::title(6),
                description: achievements::reference::Reference::description(6),
                icon: achievements::reference::Reference::icon(6),
                points: achievements::reference::Reference::points(6),
                hidden: achievements::reference::Reference::hidden(6),
                index: achievements::reference::Reference::index(6),
                group: achievements::reference::Reference::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::FillerOne => MetadataTrait::new(
                title: achievements::filler::Filler::title(0),
                description: achievements::filler::Filler::description(0),
                icon: achievements::filler::Filler::icon(0),
                points: achievements::filler::Filler::points(0),
                hidden: achievements::filler::Filler::hidden(0),
                index: achievements::filler::Filler::index(0),
                group: achievements::filler::Filler::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::FillerTwo => MetadataTrait::new(
                title: achievements::filler::Filler::title(1),
                description: achievements::filler::Filler::description(1),
                icon: achievements::filler::Filler::icon(1),
                points: achievements::filler::Filler::points(1),
                hidden: achievements::filler::Filler::hidden(1),
                index: achievements::filler::Filler::index(1),
                group: achievements::filler::Filler::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::FillerThree => MetadataTrait::new(
                title: achievements::filler::Filler::title(2),
                description: achievements::filler::Filler::description(2),
                icon: achievements::filler::Filler::icon(2),
                points: achievements::filler::Filler::points(2),
                hidden: achievements::filler::Filler::hidden(2),
                index: achievements::filler::Filler::index(2),
                group: achievements::filler::Filler::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::FillerFour => MetadataTrait::new(
                title: achievements::filler::Filler::title(3),
                description: achievements::filler::Filler::description(3),
                icon: achievements::filler::Filler::icon(3),
                points: achievements::filler::Filler::points(3),
                hidden: achievements::filler::Filler::hidden(3),
                index: achievements::filler::Filler::index(3),
                group: achievements::filler::Filler::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::FillerFive => MetadataTrait::new(
                title: achievements::filler::Filler::title(4),
                description: achievements::filler::Filler::description(4),
                icon: achievements::filler::Filler::icon(4),
                points: achievements::filler::Filler::points(4),
                hidden: achievements::filler::Filler::hidden(4),
                index: achievements::filler::Filler::index(4),
                group: achievements::filler::Filler::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::StreakOne => MetadataTrait::new(
                title: achievements::streak::Streak::title(0),
                description: achievements::streak::Streak::description(0),
                icon: achievements::streak::Streak::icon(0),
                points: achievements::streak::Streak::points(0),
                hidden: achievements::streak::Streak::hidden(0),
                index: achievements::streak::Streak::index(0),
                group: achievements::streak::Streak::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::StreakTwo => MetadataTrait::new(
                title: achievements::streak::Streak::title(1),
                description: achievements::streak::Streak::description(1),
                icon: achievements::streak::Streak::icon(1),
                points: achievements::streak::Streak::points(1),
                hidden: achievements::streak::Streak::hidden(1),
                index: achievements::streak::Streak::index(1),
                group: achievements::streak::Streak::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::StreakThree => MetadataTrait::new(
                title: achievements::streak::Streak::title(2),
                description: achievements::streak::Streak::description(2),
                icon: achievements::streak::Streak::icon(2),
                points: achievements::streak::Streak::points(2),
                hidden: achievements::streak::Streak::hidden(2),
                index: achievements::streak::Streak::index(2),
                group: achievements::streak::Streak::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ClaimerOne => MetadataTrait::new(
                title: achievements::claimer::Claimer::title(0),
                description: achievements::claimer::Claimer::description(0),
                icon: achievements::claimer::Claimer::icon(0),
                points: achievements::claimer::Claimer::points(0),
                hidden: achievements::claimer::Claimer::hidden(0),
                index: achievements::claimer::Claimer::index(0),
                group: achievements::claimer::Claimer::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ClaimerTwo => MetadataTrait::new(
                title: achievements::claimer::Claimer::title(1),
                description: achievements::claimer::Claimer::description(1),
                icon: achievements::claimer::Claimer::icon(1),
                points: achievements::claimer::Claimer::points(1),
                hidden: achievements::claimer::Claimer::hidden(1),
                index: achievements::claimer::Claimer::index(1),
                group: achievements::claimer::Claimer::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ClaimerThree => MetadataTrait::new(
                title: achievements::claimer::Claimer::title(2),
                description: achievements::claimer::Claimer::description(2),
                icon: achievements::claimer::Claimer::icon(2),
                points: achievements::claimer::Claimer::points(2),
                hidden: achievements::claimer::Claimer::hidden(2),
                index: achievements::claimer::Claimer::index(2),
                group: achievements::claimer::Claimer::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ClaimerFour => MetadataTrait::new(
                title: achievements::claimer::Claimer::title(3),
                description: achievements::claimer::Claimer::description(3),
                icon: achievements::claimer::Claimer::icon(3),
                points: achievements::claimer::Claimer::points(3),
                hidden: achievements::claimer::Claimer::hidden(3),
                index: achievements::claimer::Claimer::index(3),
                group: achievements::claimer::Claimer::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::ClaimerFive => MetadataTrait::new(
                title: achievements::claimer::Claimer::title(4),
                description: achievements::claimer::Claimer::description(4),
                icon: achievements::claimer::Claimer::icon(4),
                points: achievements::claimer::Claimer::points(4),
                hidden: achievements::claimer::Claimer::hidden(4),
                index: achievements::claimer::Claimer::index(4),
                group: achievements::claimer::Claimer::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::DailyMaster => MetadataTrait::new(
                title: achievements::master::Master::title(0),
                description: achievements::master::Master::description(0),
                icon: achievements::master::Master::icon(0),
                points: achievements::master::Master::points(0),
                hidden: achievements::master::Master::hidden(0),
                index: achievements::master::Master::index(0),
                group: achievements::master::Master::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::WeeklyMaster => MetadataTrait::new(
                title: achievements::master::Master::title(1),
                description: achievements::master::Master::description(1),
                icon: achievements::master::Master::icon(1),
                points: achievements::master::Master::points(1),
                hidden: achievements::master::Master::hidden(1),
                index: achievements::master::Master::index(1),
                group: achievements::master::Master::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::KingI => MetadataTrait::new(
                title: achievements::king::King::title(0),
                description: achievements::king::King::description(0),
                icon: achievements::king::King::icon(0),
                points: achievements::king::King::points(0),
                hidden: achievements::king::King::hidden(0),
                index: achievements::king::King::index(0),
                group: achievements::king::King::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::KingII => MetadataTrait::new(
                title: achievements::king::King::title(1),
                description: achievements::king::King::description(1),
                icon: achievements::king::King::icon(1),
                points: achievements::king::King::points(1),
                hidden: achievements::king::King::hidden(1),
                index: achievements::king::King::index(1),
                group: achievements::king::King::group(),
                rewards: array![].span(),
                data: "",
            ),
            Achievement::KingIII => MetadataTrait::new(
                title: achievements::king::King::title(2),
                description: achievements::king::King::description(2),
                icon: achievements::king::King::icon(2),
                points: achievements::king::King::points(2),
                hidden: achievements::king::King::hidden(2),
                index: achievements::king::King::index(2),
                group: achievements::king::King::group(),
                rewards: array![].span(),
                data: "",
            ),
        }
    }
}

impl IntoAchievementU8 of core::traits::Into<Achievement, u8> {
    fn into(self: Achievement) -> u8 {
        match self {
            Achievement::None => 0,
            Achievement::GrinderI => 1,
            Achievement::GrinderII => 2,
            Achievement::GrinderIII => 3,
            Achievement::GrinderIV => 4,
            Achievement::GrinderV => 5,
            Achievement::ReferenceI => 6,
            Achievement::ReferenceII => 7,
            Achievement::ReferenceIII => 8,
            Achievement::ReferenceIV => 9,
            Achievement::ReferenceV => 10,
            Achievement::ReferenceVI => 11,
            Achievement::ReferenceVII => 12,
            Achievement::FillerOne => 13,
            Achievement::FillerTwo => 14,
            Achievement::FillerThree => 15,
            Achievement::FillerFour => 16,
            Achievement::FillerFive => 17,
            Achievement::StreakOne => 18,
            Achievement::StreakTwo => 19,
            Achievement::StreakThree => 20,
            Achievement::ClaimerOne => 21,
            Achievement::ClaimerTwo => 22,
            Achievement::ClaimerThree => 23,
            Achievement::ClaimerFour => 24,
            Achievement::ClaimerFive => 25,
            Achievement::DailyMaster => 26,
            Achievement::WeeklyMaster => 27,
            Achievement::KingI => 28,
            Achievement::KingII => 29,
            Achievement::KingIII => 30,
        }
    }
}

impl IntoU8Achievement of core::traits::Into<u8, Achievement> {
    fn into(self: u8) -> Achievement {
        let card: felt252 = self.into();
        match card {
            0 => Achievement::None,
            1 => Achievement::GrinderI,
            2 => Achievement::GrinderII,
            3 => Achievement::GrinderIII,
            4 => Achievement::GrinderIV,
            5 => Achievement::GrinderV,
            6 => Achievement::ReferenceI,
            7 => Achievement::ReferenceII,
            8 => Achievement::ReferenceIII,
            9 => Achievement::ReferenceIV,
            10 => Achievement::ReferenceV,
            11 => Achievement::ReferenceVI,
            12 => Achievement::ReferenceVII,
            13 => Achievement::FillerOne,
            14 => Achievement::FillerTwo,
            15 => Achievement::FillerThree,
            16 => Achievement::FillerFour,
            17 => Achievement::FillerFive,
            18 => Achievement::StreakOne,
            19 => Achievement::StreakTwo,
            20 => Achievement::StreakThree,
            21 => Achievement::ClaimerOne,
            22 => Achievement::ClaimerTwo,
            23 => Achievement::ClaimerThree,
            24 => Achievement::ClaimerFour,
            25 => Achievement::ClaimerFive,
            26 => Achievement::DailyMaster,
            27 => Achievement::WeeklyMaster,
            28 => Achievement::KingI,
            29 => Achievement::KingII,
            30 => Achievement::KingIII,
            _ => Achievement::None,
        }
    }
}

